name: Format PHP

on:
  push:
    branches:
      - main
  pull_request:
  # pull_request_target:
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    # container:
      # image: ros:noetic-ros-core

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    # - uses: stefanzweifel/git-auto-commit-action@v4
    - uses: stefanzweifel/git-auto-commit-action@fix/fail-if-git-not-available
      id: commit
      # with:
        # file_pattern: "**/*.php tests/*.php"
        # file_pattern: "**.php"
        # disable_globbing: true

    - name: "Run if changes have been detected (bool)"
      if: ${{ steps.commit.outputs.changes_detected }} == 1
      run: echo "Changes!"

    - name: "Run if no changes have been detected (bool)"
      if: ${{ steps.commit.outputs.changes_detected }} == 0
      run: echo "No Changes!"

    - name: GITHUB_OUTPUT value
      run: echo $GITHUB_OUTPUT
