name: Format PHP

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: stefanzweifel/git-auto-commit-action@master
      id: commit
      with:
        branch: create-tag-in-branch
        tagging_message: 'v0.4.0'

    - name: "Run if changes have been detected (bool)"
      if: ${{ steps.commit.outputs.changes_detected }} == 1
      run: echo "Changes!"

    - name: "Run if no changes have been detected (bool)"
      if: ${{ steps.commit.outputs.changes_detected }} == 0
      run: echo "No Changes!"
