name: Format PHP

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      with:
        commit_message: Apply php-cs-fixer changes
        commit_options: '-n -s'

        commit_user_name: Custom GitHub Actions
        commit_user_email: bot@github.com

      - name: "Run if changes have been detected"
        if: ${{ steps.commit.outputs.changes_detected }} == "true"
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: ${{ steps.commit.outputs.changes_detected }} == "false"
        run: echo "No Changes!"
