name: Format PHP

on: push

defaults:
  run:
    shell: bash

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: stefanzweifel/git-auto-commit-action@fix-67
      with:
        commit_message: Apply php-cs-fixer changes
        tagging_message: 'v1.1.0'
        file_pattern: app/*.php

        commit_user_name: Custom GitHub Actions
        commit_user_email: bot@github.com
