name: Format PHP

on: pull_request

# on:
#   push:
#     branches:
#       - master

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    # - uses: stefanzweifel/git-auto-commit-action@master
    - uses: yelizariev/git-auto-commit-action@custom-repo-path
      with:
        commit_message: Apply php-cs-fixer changes
        commit_options: '--no-verify'
        # branch: master
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
