name: Format PHP

on: pull_request

# on:
#   push:
#     branches:
#       - master

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: gomorizsolt/git-auto-commit-action@issue-14_support-custom-git-params
    # - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Apply php-cs-fixer changes
        commit_options: '--no-verify'
        file_pattern: '.'
        # branch: master
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
