name: Format PHP

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      with:
        file_pattern: "**/*.php tests/*.php"
        disable_globbing: true

    - name: "Run if changes have been detected (bool)"
      if: ${{ steps.commit.outputs.changes_detected }} == 1
      run: echo "Changes!"

    - name: "Run if no changes have been detected (bool)"
      if: ${{ steps.commit.outputs.changes_detected }} == 0
      run: echo "No Changes!"
