name: PHP Insights

on: push

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: MilesChou/composer-action@master
      with:
        args: install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - uses: stefanzweifel/laravel-phpinsights-action@v1.0.0
      with:
        args: -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80 --disable-security-check
