name: refresh

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: "recursive"

      - name: Install python and dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # NOTE: here I have a script that creates new files. I simplify it for debugging.
      - name: Create a dummy file
        run: touch dummy-$(date '+%Y%m%d%H%M%S').txt

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "chore: refresh files"
          branch: master
